### ISSUE TITLE
Invalid import path and invalid paths to font assets

### ISSUE THREAD

**Issue by DimitarAbix** [ra-tes/style-guide#1]
### Description
Upon installing (updating) the package I tried to import it via the path given in the documentation

> import 'living-style-guide/bin/materialize.css'

This path does not work.
Upon opening the node module and discovered that the path doesn't exist, and that the path to the materialize.css is 
> import 'living-style-guide/dist/css/materialize.css'

The import worked, but this revealed another issue.

When building the project, the build threw 20 Errors about a module not being found, all pertaining relative paths to fonts, which I again checked in the node module package, do not exist in the path, but are in a different place in the package.

The fonts in questions are all from the roboto familly of fonts

### Error Message
This repeats for all 20 paths
```
Error in ./~/living-style-guide/dist/css/materialize.css
Module not found: ../fonts/roboto/Roboto-Thin.eot in /project/node_modules/living-style-guide/dist/css
```

**Comment by mrsergeysh** [comment]
Thanks for reporting.

Please update with a new version. This issue has been resolved. 

P.S. You can just `import 'living-style-guide';` now. No need to import the css file explicitly.
